fragment ImageSquareFragment on FileFieldInterface {
	format
	id
	mimeType
	url
	title
	responsiveImage(imgixParams: { ar: "4:3", fit: crop, w: 800, h: 800, auto: format }) {
		...ResponsiveImageFragment
	}
}
