query Contact {
	contact {
		...ContactFragment
	}
}

query AllContacts {
	allContacts {
		...ContactFragment
	}
}

fragment ContactFragment on ContactRecord {
	id
	email
	name
	phone
	text
	portrait {
		...ImageFragment
	}
}
