query Contact($locale: SiteLocale) {
	contact(locale: $locale) {
		...ContactFragment
	}
}

query AllContacts($locale: SiteLocale) {
	allContacts(first: 100, locale: $locale) {
		...ContactFragment
	}
}

fragment ContactFragment on ContactRecord {
	id
	email
	name
	phone
	text
	portrait {
		...ImageFragment
	}
}
