query Manifest($locale: SiteLocale) {
	manifest(locale: $locale) {
		id
		title
		video {
			...VideoFragment
		}
		headline {
			blocks
			links
			value
		}
		intro {
			blocks
			links
			value
		}
		text {
			blocks
			links
			value
		}
	}
}
