query Manifest {
	manifest {
		id
		title
		video {
			...VideoFragment
		}
		headline {
			blocks
			links
			value
		}
		intro {
			blocks
			links
			value
		}
		text {
			blocks
			links
			value
		}
	}
}
