query Portfolio($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale) {
	portfolioHeadline(locale: $locale) {
		headline {
			blocks
			links
			value
		}
	}
	allCompanies(first: $first, skip: $skip, locale: $locale) {
		...CompanyFragment
	}
	_allCompaniesMeta(locale: $locale) {
		count
	}
}

fragment CompanyFragment on CompanyRecord {
	id
	name
	url
	text {
		blocks
		links
		value
	}
	image {
		...ImageSquareFragment
	}
}
