query Start($locale: SiteLocale) {
	start(locale: $locale) {
		id
		video {
			...MediaFragment
		}
		facts {
			id
			label
			number
		}
		headline {
			blocks
			links
			value
		}
		text {
			blocks
			links
			value
		}
		textIntro {
			blocks
			links
			value
		}
		summary {
			blocks
			links
			value
			inlineBlocks {
				... on InlineVideoBlockRecord {
					__typename
					id
					video {
						...MediaFragment
					}
				}
			}
		}
		portfolio {
			...CompanyFragment
		}
	}
	portfolioHeadline(locale: $locale) {
		id
		headline {
			blocks
			links
			value
		}
	}
}
