query You($locale: SiteLocale) {
	you(locale: $locale) {
		id
		title
		headline {
			blocks
			links
			value
		}
		inevestHeadline
		investText {
			blocks
			links
			value
		}
		text {
			blocks
			links
			value
		}
	}
}
